package POJOs;
// Generated 7/10/2023 10:40:27 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codigoCliente;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModificacion;
     private boolean estado;
     private String nombreCliente;
     private String apellidoCliente;
     private String direccionCliente;
     private String ciudadCliente;
     private Date fechaIngreso;
     private Date fechaModificacion;
     private Set<DetalleFac> detalleFacs = new HashSet<DetalleFac>(0);

    public Cliente() {
    }

	
    public Cliente(boolean estado, String nombreCliente, String apellidoCliente, String direccionCliente, String ciudadCliente) {
        this.estado = estado;
        this.nombreCliente = nombreCliente;
        this.apellidoCliente = apellidoCliente;
        this.direccionCliente = direccionCliente;
        this.ciudadCliente = ciudadCliente;
    }
    public Cliente(Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModificacion, boolean estado, String nombreCliente, String apellidoCliente, String direccionCliente, String ciudadCliente, Date fechaIngreso, Date fechaModificacion, Set<DetalleFac> detalleFacs) {
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
       this.estado = estado;
       this.nombreCliente = nombreCliente;
       this.apellidoCliente = apellidoCliente;
       this.direccionCliente = direccionCliente;
       this.ciudadCliente = ciudadCliente;
       this.fechaIngreso = fechaIngreso;
       this.fechaModificacion = fechaModificacion;
       this.detalleFacs = detalleFacs;
    }
   
    public Integer getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(Integer codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModificacion() {
        return this.usuarioByUsuarioModificacion;
    }
    
    public void setUsuarioByUsuarioModificacion(Usuario usuarioByUsuarioModificacion) {
        this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidoCliente() {
        return this.apellidoCliente;
    }
    
    public void setApellidoCliente(String apellidoCliente) {
        this.apellidoCliente = apellidoCliente;
    }
    public String getDireccionCliente() {
        return this.direccionCliente;
    }
    
    public void setDireccionCliente(String direccionCliente) {
        this.direccionCliente = direccionCliente;
    }
    public String getCiudadCliente() {
        return this.ciudadCliente;
    }
    
    public void setCiudadCliente(String ciudadCliente) {
        this.ciudadCliente = ciudadCliente;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<DetalleFac> getDetalleFacs() {
        return this.detalleFacs;
    }
    
    public void setDetalleFacs(Set<DetalleFac> detalleFacs) {
        this.detalleFacs = detalleFacs;
    }




}


