package POJOs;
// Generated 7/10/2023 10:40:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetalleFac generated by hbm2java
 */
public class DetalleFac  implements java.io.Serializable {


     private Integer noFactura;
     private Cliente cliente;
     private Producto producto;
     private TipoPago tipoPago;
     private Usuario usuarioByUsuarioModificacion;
     private Usuario usuarioByUsuarioIngreso;
     private boolean estado;
     private Date fecha;
     private Boolean estadoFinalizado;
     private Date fechaIngreso;
     private Date fechaModificacion;

    public DetalleFac() {
    }

	
    public DetalleFac(Cliente cliente, Producto producto, boolean estado) {
        this.cliente = cliente;
        this.producto = producto;
        this.estado = estado;
    }
    public DetalleFac(Cliente cliente, Producto producto, TipoPago tipoPago, Usuario usuarioByUsuarioModificacion, Usuario usuarioByUsuarioIngreso, boolean estado, Date fecha, Boolean estadoFinalizado, Date fechaIngreso, Date fechaModificacion) {
       this.cliente = cliente;
       this.producto = producto;
       this.tipoPago = tipoPago;
       this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.estado = estado;
       this.fecha = fecha;
       this.estadoFinalizado = estadoFinalizado;
       this.fechaIngreso = fechaIngreso;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getNoFactura() {
        return this.noFactura;
    }
    
    public void setNoFactura(Integer noFactura) {
        this.noFactura = noFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public TipoPago getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(TipoPago tipoPago) {
        this.tipoPago = tipoPago;
    }
    public Usuario getUsuarioByUsuarioModificacion() {
        return this.usuarioByUsuarioModificacion;
    }
    
    public void setUsuarioByUsuarioModificacion(Usuario usuarioByUsuarioModificacion) {
        this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getEstadoFinalizado() {
        return this.estadoFinalizado;
    }
    
    public void setEstadoFinalizado(Boolean estadoFinalizado) {
        this.estadoFinalizado = estadoFinalizado;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


