package POJOs;
// Generated 7/10/2023 10:40:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private Usuario usuarioByUsuarioModificacion;
     private Usuario usuarioByUsuarioIngreso;
     private String nombreApellido;
     private Date fechaIngreso;
     private Date fechaModificacion;

    public Empleado() {
    }

    public Empleado(Usuario usuarioByUsuarioModificacion, Usuario usuarioByUsuarioIngreso, String nombreApellido, Date fechaIngreso, Date fechaModificacion) {
       this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.nombreApellido = nombreApellido;
       this.fechaIngreso = fechaIngreso;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Usuario getUsuarioByUsuarioModificacion() {
        return this.usuarioByUsuarioModificacion;
    }
    
    public void setUsuarioByUsuarioModificacion(Usuario usuarioByUsuarioModificacion) {
        this.usuarioByUsuarioModificacion = usuarioByUsuarioModificacion;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public String getNombreApellido() {
        return this.nombreApellido;
    }
    
    public void setNombreApellido(String nombreApellido) {
        this.nombreApellido = nombreApellido;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


