package POJOs;
// Generated 7/10/2023 10:40:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private Integer idProveedor;
     private Usuario usuarioByUsuarioIngreso;
     private Usuario usuarioByUsuarioModifica;
     private boolean estado;
     private String nombre;
     private String telefono;
     private String direccion;
     private String correo;
     private Date fechaIngreso;
     private Date fechaModifica;

    public Proveedores() {
    }

	
    public Proveedores(boolean estado) {
        this.estado = estado;
    }
    public Proveedores(Usuario usuarioByUsuarioIngreso, Usuario usuarioByUsuarioModifica, boolean estado, String nombre, String telefono, String direccion, String correo, Date fechaIngreso, Date fechaModifica) {
       this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
       this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
       this.estado = estado;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.correo = correo;
       this.fechaIngreso = fechaIngreso;
       this.fechaModifica = fechaModifica;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Usuario getUsuarioByUsuarioIngreso() {
        return this.usuarioByUsuarioIngreso;
    }
    
    public void setUsuarioByUsuarioIngreso(Usuario usuarioByUsuarioIngreso) {
        this.usuarioByUsuarioIngreso = usuarioByUsuarioIngreso;
    }
    public Usuario getUsuarioByUsuarioModifica() {
        return this.usuarioByUsuarioModifica;
    }
    
    public void setUsuarioByUsuarioModifica(Usuario usuarioByUsuarioModifica) {
        this.usuarioByUsuarioModifica = usuarioByUsuarioModifica;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaModifica() {
        return this.fechaModifica;
    }
    
    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }




}


