package POJOs;
// Generated 7/10/2023 10:40:27 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPago generated by hbm2java
 */
public class TipoPago  implements java.io.Serializable {


     private Integer codigoPago;
     private String formaPago;
     private Set<DetalleFac> detalleFacs = new HashSet<DetalleFac>(0);

    public TipoPago() {
    }

	
    public TipoPago(String formaPago) {
        this.formaPago = formaPago;
    }
    public TipoPago(String formaPago, Set<DetalleFac> detalleFacs) {
       this.formaPago = formaPago;
       this.detalleFacs = detalleFacs;
    }
   
    public Integer getCodigoPago() {
        return this.codigoPago;
    }
    
    public void setCodigoPago(Integer codigoPago) {
        this.codigoPago = codigoPago;
    }
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }
    public Set<DetalleFac> getDetalleFacs() {
        return this.detalleFacs;
    }
    
    public void setDetalleFacs(Set<DetalleFac> detalleFacs) {
        this.detalleFacs = detalleFacs;
    }




}


